Repository Hackathons-UK/wiki, pull requests merged in 2020-02, with the labels that each got.

#131 Moved Royal Hackaway v3 to Past Events
  docs/index.md
Labels: past events

#133 Moved Royal Hackaway v3 to Past Events
  docs/index.md
Labels: WIP, past events

#145 Added StudentHack 8
  docs/index.md
Labels: New event

#148 Update Tech Page
  .gitignore
  .vscode/settings.json
  docs/organise/before/tech.md
Labels: WIP

#151 Move 2nd weekend of February events to Past Events
  docs/attend/workshops.md
  docs/index.md
Labels: past events

#173 Change University header to Location
  docs/index.md
Labels: enhancement

#174 Add rough date for HackTheMidlands 5.0
  docs/index.md
Labels: New event
